# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from app.api.base.controller import BaseView
from app.api.rbac.service import RBACService

from external.protocol.python.authority_list_request import AuthorityListRequest
from external.protocol.python.authority_list_response import AuthorityListResponse
from external.protocol.python.menu_create_request import MenuCreateRequest
from external.protocol.python.menu_create_response import MenuCreateResponse
from external.protocol.python.menu_list_request import MenuListRequest
from external.protocol.python.menu_list_response import MenuListResponse
from external.protocol.python.role_create_request import RoleCreateRequest
from external.protocol.python.role_create_response import RoleCreateResponse


class RoleCreateView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = RoleCreateRequest
	response_protocol = RoleCreateResponse
	view_func = {
		"post": RBACService.role_create
	}


class AuthorityListView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = AuthorityListRequest
	response_protocol = AuthorityListResponse
	view_func = {
		"post": RBACService.authority_list
	}


class MenuListView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = MenuListRequest
	response_protocol = MenuListResponse
	view_func = {
		"post": RBACService.menu_list
	}


class MenuCreateView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = MenuCreateRequest
	response_protocol = MenuCreateResponse
	view_func = {
		"post": RBACService.menu_create
	}

