# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from external.protocol.python.login_request import LoginRequest
from external.protocol.python.login_response import LoginResponse
from external.protocol.python.register_request import RegisterRequest
from external.protocol.python.register_response import RegisterResponse

class RBACService(object):
	"""
	权限服务
	"""
	@classmethod
	def login(cls, request: LoginRequest, response: LoginResponse):
		"""
		角色创建
		"""
		pass


	@classmethod
	def register(cls, request: RegisterRequest, response: RegisterResponse):
		"""
		权限创建
		"""
		pass


