# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from external.protocol.python.add_permission_request import AddPermissionRequest
from external.protocol.python.add_permission_response import AddPermissionResponse
from external.protocol.python.add_role_request import AddRoleRequest
from external.protocol.python.add_role_response import AddRoleResponse
from external.protocol.python.add_user_permission_request import AddUserPermissionRequest
from external.protocol.python.add_user_permission_response import AddUserPermissionResponse
from external.protocol.python.add_user_role_request import AddUserRoleRequest
from external.protocol.python.add_user_role_response import AddUserRoleResponse
from external.protocol.python.alter_role_request import AlterRoleRequest
from external.protocol.python.alter_role_response import AlterRoleResponse
from external.protocol.python.delete_permission_request import DeletePermissionRequest
from external.protocol.python.delete_permission_response import DeletePermissionResponse
from external.protocol.python.delete_role_request import DeleteRoleRequest
from external.protocol.python.delete_role_response import DeleteRoleResponse
from external.protocol.python.delete_user_permission_request import DeleteUserPermissionRequest
from external.protocol.python.delete_user_permission_response import DeleteUserPermissionResponse
from external.protocol.python.delete_user_role_request import DeleteUserRoleRequest
from external.protocol.python.delete_user_role_response import DeleteUserRoleResponse
from external.protocol.python.permission_detail import *
from external.protocol.python.query_permissions_request import QueryPermissionsRequest
from external.protocol.python.query_permissions_response import QueryPermissionsResponse
from external.protocol.python.query_roles_request import QueryRolesRequest
from external.protocol.python.query_roles_response import QueryRolesResponse
from external.protocol.python.query_user_permissions_request import QueryUserPermissionsRequest
from external.protocol.python.query_user_permissions_response import QueryUserPermissionsResponse
from external.protocol.python.query_user_roles_request import QueryUserRolesRequest
from external.protocol.python.query_user_roles_response import QueryUserRolesResponse
from external.protocol.python.role_detail import *

class RBACService(object):
	"""
	权限服务
	"""
	@classmethod
	def add_role(cls, request: AddRoleRequest, response: AddRoleResponse):
		"""
		增加角色
		"""
		pass


	@classmethod
	def delete_role(cls, request: DeleteRoleRequest, response: DeleteRoleResponse):
		"""
		删除角色
		"""
		pass


	@classmethod
	def alter_role(cls, request: AlterRoleRequest, response: AlterRoleResponse):
		"""
		修改角色
		"""
		pass


	@classmethod
	def query_roles(cls, request: QueryRolesRequest, response: QueryRolesResponse):
		"""
		查询角色列表
		"""
		pass


	@classmethod
	def add_permission(cls, request: AddPermissionRequest, response: AddPermissionResponse):
		"""
		增加权限
		"""
		pass


	@classmethod
	def delete_permission(cls, request: DeletePermissionRequest, response: DeletePermissionResponse):
		"""
		删除权限
		"""
		pass


	@classmethod
	def query_permissions(cls, request: QueryPermissionsRequest, response: QueryPermissionsResponse):
		"""
		查询权限列表
		"""
		pass


	@classmethod
	def add_user_permission(cls, request: AddUserPermissionRequest, response: AddUserPermissionResponse):
		"""
		增加角色权限
		"""
		pass


	@classmethod
	def delete_user_permission(cls, request: DeleteUserPermissionRequest, response: DeleteUserPermissionResponse):
		"""
		删除角色权限
		"""
		pass


	@classmethod
	def query_user_permissions(cls, request: QueryUserPermissionsRequest, response: QueryUserPermissionsResponse):
		"""
		查询角色权限
		"""
		pass


	@classmethod
	def add_user_role(cls, request: AddUserRoleRequest, response: AddUserRoleResponse):
		"""
		增加用户角色
		"""
		pass


	@classmethod
	def delete_user_role(cls, request: DeleteUserRoleRequest, response: DeleteUserRoleResponse):
		"""
		删除用户角色
		"""
		pass


	@classmethod
	def query_user_roles(cls, request: QueryUserRolesRequest, response: QueryUserRolesResponse):
		"""
		查询用户角色
		"""
		pass


