version: '3.0'
services:
  mysql:
    build:
      context: deploy/mysql
      dockerfile: Dockerfile
    container_name: robot_db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root # root密码
      MYSQL_DATABASE: robot_db
    volumes:
      - "/usr/local/docker/mydata/mysql/data:/var/lib/mysql" # 存放数据文件
      - "/usr/local/docker/mydata/mysql/log:/var/log/mysql"  # 存放日志文件

  redis:
    build:
      context: deploy/redis
      dockerfile: Dockerfile
    container_name: robot_redis
    volumes:
      - /usr/local/docker/mydata/redis/data:/data
    restart: always
    ports:
      - "16379:6379"