version: '3.0'
services:
  mysql:
    build:
      context: deploy/mysql
      dockerfile: Dockerfile
    container_name: my_db
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root # root密码
      MYSQL_DATABASE: my_db
    volumes:
      - "/app/mysql/data:/var/lib/mysql" # 存放数据文件
      - "/app/mysql/log:/var/log/mysql"  # 存放日志文件

  redis:
    build:
      context: deploy/redis
      dockerfile: Dockerfile
    container_name: my_redis
    volumes:
      - /app/redis/data:/data
    restart: always
    ports:
      - "16379:6379"