# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from app.api.base.controller import BaseView
from app.api.auth.service import AuthService

from external.protocol.python.login_request import LoginRequest
from external.protocol.python.login_response import LoginResponse
from external.protocol.python.register_request import RegisterRequest
from external.protocol.python.register_response import RegisterResponse


class LoginView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = LoginRequest
	response_protocol = LoginResponse
	view_func = {
		"post": AuthService.login
	}


class RegisterView(BaseView):
	decorators = ()     # 前置接口
	
	methods = ["POST"]  # 允许的请求方式
	request_protocol  = RegisterRequest
	response_protocol = RegisterResponse
	view_func = {
		"post": AuthService.register
	}

