# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from external.protocol.python.get_user_info_request import GetUserInfoRequest
from external.protocol.python.get_user_info_response import GetUserInfoResponse
from external.protocol.python.login_request import LoginRequest
from external.protocol.python.login_response import LoginResponse
from external.protocol.python.register_request import RegisterRequest
from external.protocol.python.register_response import RegisterResponse
from external.protocol.python.role_detail import *

class AuthService(object):
	"""
	认证服务
	"""
	@classmethod
	def login(cls, request: LoginRequest, response: LoginResponse):
		"""
		登录
		"""
		pass


	@classmethod
	def register(cls, request: RegisterRequest, response: RegisterResponse):
		"""
		注册
		"""
		pass


	@classmethod
	def get_user_info(cls, request: GetUserInfoRequest, response: GetUserInfoResponse):
		"""
		获取用户信息
		"""
		pass


