# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""
from flask import Flask
from flask.blueprints import Blueprint

from app.api.demo.controller import AddDemoView
from app.api.demo.controller import QueryDemoView
from app.api.demo.controller import QueryDemosView
from app.api.demo.controller import AlterDemoView
from app.api.demo.controller import DeleteDemoView
from app.api.rbac.controller import RoleCreateView
from app.api.rbac.controller import AuthorityListView
from app.api.rbac.controller import MenuListView
from app.api.rbac.controller import MenuCreateView
from app.api.auth.controller import LoginView
from app.api.auth.controller import RegisterView

router = Blueprint('api', __name__)

def route_register(app: Flask):
	# service: 示例服务 owner: andy.mei@momenta.ai
	router.add_url_rule('/api/v1/demo/add_demo', view_func = AddDemoView.as_view('add_demo')) # 1.添加demo
	router.add_url_rule('/api/v1/demo/query_demo', view_func = QueryDemoView.as_view('query_demo')) # 2.查询demo
	router.add_url_rule('/api/v1/demo/query_demos', view_func = QueryDemosView.as_view('query_demos')) # 3.查询demo列表
	router.add_url_rule('/api/v1/demo/alter_demo', view_func = AlterDemoView.as_view('alter_demo')) # 4.修改demo
	router.add_url_rule('/api/v1/demo/delete_demo', view_func = DeleteDemoView.as_view('delete_demo')) # 5.删除demo

	# service: 权限服务 owner: 施意波
	router.add_url_rule('/api/v1/auth/role_create', view_func = RoleCreateView.as_view('role_create')) # 1.角色创建
	router.add_url_rule('/api/v1/authority_list', view_func = AuthorityListView.as_view('authority_list')) # 2.权限列表
	router.add_url_rule('/api/v1/menu_list', view_func = MenuListView.as_view('menu_list')) # 3.菜单列表
	router.add_url_rule('/api/v1/menu_create', view_func = MenuCreateView.as_view('menu_create')) # 4.菜单创建

	# service: 认证服务 owner: andy.mei@momenta.ai
	router.add_url_rule('/api/v1/login', view_func = LoginView.as_view('login')) # 1.登录
	router.add_url_rule('/api/v1/register', view_func = RegisterView.as_view('register')) # 2.注册

	app.register_blueprint(router)