mysql:
  host: 127.0.0.1
  port: 14006
  username: robot
  password: robot
  db: robot_db
  autocommit: true

redis:
  host: 127.0.0.1
  port: 16379
  password: robot
  charset: utf-8
  db: 0
  decode_response: True

jwt:
  key: d41d8cd98f00b204e9800998ecf8427e
  ex: 60
  algorithm: HS256