mysql:
  host: 127.0.0.1
  port: 13306
  username: my_platform
  password: my_platform
  db: my_db
  autocommit: true

redis:
  host: 127.0.0.1
  port: 16379
  password: my_platform
  charset: utf-8
  db: 0
  decode_response: True

jwt:
  key: d41d8cd98f00b204e9800998ecf8427e
  ex: 60
  algorithm: HS256