# -*- coding: utf-8 -*-
"""
The file auto generated by tool genapi, Do not modify.
"""

from external.protocol.python.add_demo_request import AddDemoRequest
from external.protocol.python.add_demo_response import AddDemoResponse
from external.protocol.python.alter_demo_request import AlterDemoRequest
from external.protocol.python.alter_demo_response import AlterDemoResponse
from external.protocol.python.delete_demo_request import DeleteDemoRequest
from external.protocol.python.delete_demo_response import DeleteDemoResponse
from external.protocol.python.query_demos_request import QueryDemosRequest
from external.protocol.python.query_demos_response import QueryDemosResponse

class DemoService(object):
	"""
	示例服务
	"""
	@classmethod
	def add_demo(cls, request: AddDemoRequest, response: AddDemoResponse):
		"""
		增加demo
		"""
		pass


	@classmethod
	def delete_demo(cls, request: DeleteDemoRequest, response: DeleteDemoResponse):
		"""
		删除demo
		"""
		pass


	@classmethod
	def alter_demo(cls, request: AlterDemoRequest, response: AlterDemoResponse):
		"""
		修改demo
		"""
		pass


	@classmethod
	def query_demos(cls, request: QueryDemosRequest, response: QueryDemosResponse):
		"""
		查询demo列表
		"""
		pass


